FROM maven:3-openjdk-15 AS build
WORKDIR /app
# Just copy the jars needed
COPY  lib/target  ./lib/target/
WORKDIR /app/lib
CMD ["java", "-cp", "target/tapis-notifications.jar:target/dependencies/*", "edu.utexas.tacc.tapis.notifications.lib.WorkerApplication"]

